### PR TITLE
suggestion: using pecentage from edge to trigger page turn

### PR DESCRIPTION
**Pull request by cesine**
nexus 10 has so many pixels that the page turn wouldnt trigger unless the user can really hit the edge
which is not possible if it is in a case.

### CODE REVIEW

**Comment by briangriffey** [comment]
I'm not sure that this is the correct solution. I think a better change would be to use the ViewConfiguration to distinguish swipes similar to the ViewPager onTouch method. Swiping from any place in the page should result in a started page movement.

**Comment by cesine** [comment]
alright, i'll look into that! i was starting to look at the onTouch warning anyway "PageTurnLayout overrides onTouchEvent but not performClick"

**Comment by briangriffey** [comment]
Yea, the whole touch model kind of needs to be redone. It also probably needs to move to a adapter style page fetching scheme.  Probably needs to go to a ViewGroup instead of just a FrameLayout.

**Comment by cesine** [comment]
i converted the lib to use ViewPager... pushed here: https://github.com/cesine/book-animation/tree/viewPager

summary: the scroll left and right is working so we can change pages when the custom ontouch is off, and page curl still animates when it's on. Next step I might need your help. Since you seem to be online I thought i would give you an update. I will be gone for a bit, and then start seeing if i can figure out how to keep the animation.

I don't know much about the page curl animation so I might not be able to unify the scroll event with the animation. Once the animation works, there is more work after to make the change backward compatible... etc.

**Pull request closed without merging**
